// -----------------------------------------------------------------------------
// FICHIER: Core\NKCore\src\NKCore\Traits\NkTraits.cpp
// DESCRIPTION: Implémentation de Traits et métaprogrammation
// AUTEUR: Rihen
// DATE: 2026
// -----------------------------------------------------------------------------

#include "NkTraits.h"

namespace nkentseu {
    namespace core {
        // TODO: Ajouter les implémentations ici
    } // namespace core
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================