// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkClock.h
// DESCRIPTION: High-precision clock
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKCLOCK_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKCLOCK_H_INCLUDED

#include "../Core/NkTypes.h"
#include "NkDuration.h"

namespace nkentseu {
    namespace entseu {
        
        /**
         * @brief High-precision clock
         * 
         * Fournit un accès à l'horloge système haute résolution.
         * Utilise std::chrono::high_resolution_clock ou équivalent système.
         * 
         * @example
         * auto start = NkClock::Now();
         * // ... do work ...
         * auto end = NkClock::Now();
         * auto elapsed = end - start;
         * printf("Took: %s\n", elapsed.ToString().CStr());
         */
        class NkClock {
        public:
            /**
             * @brief Time point from clock
             */
            struct TimePoint {
                i64 Nanoseconds;
                
                TimePoint() : Nanoseconds(0) {}
                explicit TimePoint(i64 ns) : Nanoseconds(ns) {}
                
                NkDuration operator-(const TimePoint& other) const {
                    return NkDuration::FromNanoseconds(Nanoseconds - other.Nanoseconds);
                }
                
                TimePoint operator+(const NkDuration& duration) const {
                    return TimePoint(Nanoseconds + duration.ToNanoseconds());
                }
                
                TimePoint operator-(const NkDuration& duration) const {
                    return TimePoint(Nanoseconds - duration.ToNanoseconds());
                }
                
                bool operator==(const TimePoint& other) const {
                    return Nanoseconds == other.Nanoseconds;
                }
                
                bool operator!=(const TimePoint& other) const {
                    return Nanoseconds != other.Nanoseconds;
                }
                
                bool operator<(const TimePoint& other) const {
                    return Nanoseconds < other.Nanoseconds;
                }
                
                bool operator<=(const TimePoint& other) const {
                    return Nanoseconds <= other.Nanoseconds;
                }
                
                bool operator>(const TimePoint& other) const {
                    return Nanoseconds > other.Nanoseconds;
                }
                
                bool operator>=(const TimePoint& other) const {
                    return Nanoseconds >= other.Nanoseconds;
                }
            };
            
            // Get current time
            static TimePoint Now();
            
            // Get elapsed time since program start
            static NkDuration GetElapsedTime();
            
            // Sleep functions
            static void Sleep(const NkDuration& duration);
            static void SleepMilliseconds(i64 milliseconds);
            static void SleepMicroseconds(i64 microseconds);
            
            // Utility
            static i64 GetFrequency();  // Clock frequency in Hz
            
        private:
            static TimePoint sStartTime;
            static void InitializeStartTime();
        };
        
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKCLOCK_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================