// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkDuration.h
// DESCRIPTION: Duration representation and manipulation
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKDURATION_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKDURATION_H_INCLUDED

#include "../Core/NkTypes.h"
#include "../Core/NkString.h"

namespace nkentseu {
    namespace entseu {
        
        /**
         * @brief Duration class for time intervals
         * 
         * Représente une durée de temps avec précision nanoseconde.
         * Supporte conversion entre différentes unités.
         * 
         * @example
         * NkDuration dur = NkDuration::FromSeconds(2.5);
         * f64 ms = dur.ToMilliseconds();  // 2500.0
         * f64 us = dur.ToMicroseconds();  // 2500000.0
         */
        class NkDuration {
        private:
            i64 mNanoseconds;  // Internal storage in nanoseconds
            
        public:
            // Constructors
            NkDuration();
            explicit NkDuration(i64 nanoseconds);
            NkDuration(const NkDuration& other);
            
            // Assignment
            NkDuration& operator=(const NkDuration& other);
            
            // Factory methods
            static NkDuration FromNanoseconds(i64 nanoseconds);
            static NkDuration FromMicroseconds(i64 microseconds);
            static NkDuration FromMicroseconds(f64 microseconds);
            static NkDuration FromMilliseconds(i64 milliseconds);
            static NkDuration FromMilliseconds(f64 milliseconds);
            static NkDuration FromSeconds(i64 seconds);
            static NkDuration FromSeconds(f64 seconds);
            static NkDuration FromMinutes(i64 minutes);
            static NkDuration FromMinutes(f64 minutes);
            static NkDuration FromHours(i64 hours);
            static NkDuration FromHours(f64 hours);
            static NkDuration FromDays(i64 days);
            static NkDuration FromDays(f64 days);
            
            // Conversion methods
            i64 ToNanoseconds() const;
            f64 ToMicrosecondsF() const;
            i64 ToMicroseconds() const;
            f64 ToMillisecondsF() const;
            i64 ToMilliseconds() const;
            f64 ToSecondsF() const;
            i64 ToSeconds() const;
            f64 ToMinutesF() const;
            i64 ToMinutes() const;
            f64 ToHoursF() const;
            i64 ToHours() const;
            f64 ToDaysF() const;
            i64 ToDays() const;
            
            // Arithmetic operations
            NkDuration operator+(const NkDuration& other) const;
            NkDuration operator-(const NkDuration& other) const;
            NkDuration operator*(f64 scalar) const;
            NkDuration operator/(f64 scalar) const;
            f64 operator/(const NkDuration& other) const;
            
            NkDuration& operator+=(const NkDuration& other);
            NkDuration& operator-=(const NkDuration& other);
            NkDuration& operator*=(f64 scalar);
            NkDuration& operator/=(f64 scalar);
            
            // Unary operators
            NkDuration operator-() const;
            
            // Comparison operators
            bool operator==(const NkDuration& other) const;
            bool operator!=(const NkDuration& other) const;
            bool operator<(const NkDuration& other) const;
            bool operator<=(const NkDuration& other) const;
            bool operator>(const NkDuration& other) const;
            bool operator>=(const NkDuration& other) const;
            
            // Utility methods
            NkDuration Abs() const;
            bool IsNegative() const;
            bool IsZero() const;
            bool IsPositive() const;
            
            // String conversion
            core::NkString ToString() const;
            core::NkString ToStringPrecise() const;
            
            // Constants
            static NkDuration Zero();
            static NkDuration Max();
            static NkDuration Min();
        };
        
        // Non-member operators
        NkDuration operator*(f64 scalar, const NkDuration& duration);
        
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKDURATION_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================