// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkProfiler.h
// DESCRIPTION: Performance profiling system
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKPROFILER_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKPROFILER_H_INCLUDED

#include "../Core/NkTypes.h"
#include "../Core/NkString.h"
#include "../Containers/Sequential/NkVector.h"
#include "../Containers/Associative/NkHashMap.h"
#include "NkStopwatch.h"
#include "NkDuration.h"

namespace nkentseu {
    namespace entseu {
        
        /**
         * @brief Profile result for a single measurement
         */
        struct NkProfileResult {
            core::NkString Name;
            NkDuration Duration;
            usize CallCount;
            NkDuration MinDuration;
            NkDuration MaxDuration;
            NkDuration AvgDuration;
            NkDuration TotalDuration;
            
            NkProfileResult();
            explicit NkProfileResult(const char* name);
        };
        
        /**
         * @brief Profiler class for performance measurement
         * 
         * Système de profilage pour mesurer les performances.
         * Collecte des statistiques (min, max, avg, total, count).
         * 
         * @example
         * // Manual profiling
         * NkProfiler::BeginProfile("Update");
         * // ... code to profile ...
         * NkProfiler::EndProfile("Update");
         * 
         * // Auto profiling with RAII
         * {
         *     NK_PROFILE_SCOPE("Render");
         *     // ... code to profile ...
         * }
         * 
         * // Print results
         * NkProfiler::PrintResults();
         */
        class NkProfiler {
        private:
            struct ProfileSession {
                NkStopwatch Stopwatch;
                core::NkString Name;
                
                ProfileSession() {}
                ProfileSession(const char* name) : Name(name) {
                    Stopwatch.Start();
                }
            };
            
            static core::NkHashMap<core::NkString, NkProfileResult> sResults;
            static core::NkHashMap<core::NkString, ProfileSession> sActiveSessions;
            static bool sIsEnabled;
            
        public:
            // Control
            static void Enable();
            static void Disable();
            static bool IsEnabled();
            
            static void Clear();
            static void Reset();
            
            // Profiling
            static void BeginProfile(const char* name);
            static void EndProfile(const char* name);
            
            // Results
            static NkProfileResult GetResult(const char* name);
            static core::NkVector<NkProfileResult> GetAllResults();
            
            static void PrintResults();
            static void PrintResult(const char* name);
            static core::NkString GetResultsString();
            
            // Statistics
            static usize GetProfileCount();
            static NkDuration GetTotalTime();
            static NkProfileResult GetSlowest();
            static NkProfileResult GetFastest();
        };
        
        /**
         * @brief Scoped profiler - RAII
         * 
         * Profile automatique dans un scope.
         * 
         * @example
         * void Update() {
         *     NK_PROFILE_SCOPE("Update");
         *     // ... code ...
         * }
         */
        class NkScopedProfiler {
        private:
            core::NkString mName;
            
        public:
            explicit NkScopedProfiler(const char* name);
            ~NkScopedProfiler();
        };
        
        // Macros for easy profiling
        #define NK_PROFILE_SCOPE(name) nkentseu::entseu::NkScopedProfiler _profiler_##__LINE__(name)
        #define NK_PROFILE_FUNCTION() NK_PROFILE_SCOPE(__FUNCTION__)
        
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKPROFILER_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================