// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkStopwatch.h
// DESCRIPTION: Stopwatch for measuring time intervals
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKSTOPWATCH_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKSTOPWATCH_H_INCLUDED

#include "../Core/NkTypes.h"
#include "NkClock.h"
#include "NkDuration.h"

namespace nkentseu {
    namespace entseu {
        
        /**
         * @brief Stopwatch for precise time measurement
         * 
         * Chronomètre pour mesurer des intervalles de temps.
         * Supporte pause/reprise.
         * 
         * @example
         * NkStopwatch sw;
         * sw.Start();
         * // ... do work ...
         * sw.Stop();
         * printf("Elapsed: %s\n", sw.GetElapsed().ToString().CStr());
         * 
         * // With pause
         * sw.Reset();
         * sw.Start();
         * // work 1
         * sw.Pause();
         * // pause
         * sw.Resume();
         * // work 2
         * sw.Stop();
         */
        class NkStopwatch {
        private:
            NkClock::TimePoint mStartTime;
            NkDuration mAccumulated;
            bool mIsRunning;
            
        public:
            // Constructors
            NkStopwatch();
            
            // Control
            void Start();
            void Stop();
            void Reset();
            void Restart();
            
            void Pause();
            void Resume();
            
            // State
            bool IsRunning() const;
            bool IsPaused() const;
            
            // Time access
            NkDuration GetElapsed() const;
            f64 GetElapsedSeconds() const;
            f64 GetElapsedMilliseconds() const;
            f64 GetElapsedMicroseconds() const;
            
            // Utility - auto start on construction
            static NkStopwatch StartNew();
        };
        
        /**
         * @brief Scoped stopwatch - RAII
         * 
         * Mesure automatiquement le temps dans un scope.
         * 
         * @example
         * {
         *     NkScopedStopwatch timer("Operation");
         *     // ... do work ...
         * }  // Prints: "Operation took: 1.23s"
         */
        class NkScopedStopwatch {
        private:
            NkStopwatch mStopwatch;
            const char* mName;
            bool mPrintOnDestroy;
            
        public:
            explicit NkScopedStopwatch(const char* name = "Operation", bool printOnDestroy = true);
            ~NkScopedStopwatch();
            
            NkDuration GetElapsed() const;
            void Stop();
        };
        
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKSTOPWATCH_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================