// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkStopwatch.cpp
// DESCRIPTION: Stopwatch implementation
// AUTEUR: Rihen
// DATE: 2026-02-10
// -----------------------------------------------------------------------------

#include "NkStopwatch.h"
#include <cstdio>

namespace nkentseu {
    namespace entseu {
        
        NkStopwatch::NkStopwatch()
            : mStartTime()
            , mAccumulated(NkDuration::Zero())
            , mIsRunning(false) {
        }
        
        void NkStopwatch::Start() {
            if (!mIsRunning) {
                mStartTime = NkClock::Now();
                mIsRunning = true;
            }
        }
        
        void NkStopwatch::Stop() {
            if (mIsRunning) {
                NkClock::TimePoint now = NkClock::Now();
                mAccumulated += (now - mStartTime);
                mIsRunning = false;
            }
        }
        
        void NkStopwatch::Reset() {
            mAccumulated = NkDuration::Zero();
            mIsRunning = false;
        }
        
        void NkStopwatch::Restart() {
            Reset();
            Start();
        }
        
        void NkStopwatch::Pause() {
            Stop();
        }
        
        void NkStopwatch::Resume() {
            Start();
        }
        
        bool NkStopwatch::IsRunning() const {
            return mIsRunning;
        }
        
        bool NkStopwatch::IsPaused() const {
            return !mIsRunning && !mAccumulated.IsZero();
        }
        
        NkDuration NkStopwatch::GetElapsed() const {
            NkDuration elapsed = mAccumulated;
            
            if (mIsRunning) {
                NkClock::TimePoint now = NkClock::Now();
                elapsed += (now - mStartTime);
            }
            
            return elapsed;
        }
        
        f64 NkStopwatch::GetElapsedSeconds() const {
            return GetElapsed().ToSecondsF();
        }
        
        f64 NkStopwatch::GetElapsedMilliseconds() const {
            return GetElapsed().ToMillisecondsF();
        }
        
        f64 NkStopwatch::GetElapsedMicroseconds() const {
            return GetElapsed().ToMicrosecondsF();
        }
        
        NkStopwatch NkStopwatch::StartNew() {
            NkStopwatch sw;
            sw.Start();
            return sw;
        }
        
        // NkScopedStopwatch
        NkScopedStopwatch::NkScopedStopwatch(const char* name, bool printOnDestroy)
            : mStopwatch()
            , mName(name)
            , mPrintOnDestroy(printOnDestroy) {
            mStopwatch.Start();
        }
        
        NkScopedStopwatch::~NkScopedStopwatch() {
            mStopwatch.Stop();
            
            if (mPrintOnDestroy) {
                printf("%s took: %s\n", mName, mStopwatch.GetElapsed().ToString().CStr());
            }
        }
        
        NkDuration NkScopedStopwatch::GetElapsed() const {
            return mStopwatch.GetElapsed();
        }
        
        void NkScopedStopwatch::Stop() {
            mStopwatch.Stop();
            mPrintOnDestroy = false;
        }
        
    } // namespace entseu
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================