// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkTimer.cpp
// DESCRIPTION: Timer implementation
// AUTEUR: Rihen
// DATE: 2026-02-10
// -----------------------------------------------------------------------------

#include "NkTimer.h"

namespace nkentseu {
    namespace entseu {
        
        NkTimer::NkTimer()
            : mCallback(nullptr)
            , mInterval(NkDuration::FromSeconds(1))
            , mLastTick()
            , mIsRunning(false)
            , mAutoReset(true) {
        }
        
        NkTimer::NkTimer(NkTimerCallback* callback, const NkDuration& interval, bool autoReset)
            : mCallback(callback)
            , mInterval(interval)
            , mLastTick()
            , mIsRunning(false)
            , mAutoReset(autoReset) {
        }
        
        void NkTimer::Start() {
            if (!mIsRunning) {
                mLastTick = NkClock::Now();
                mIsRunning = true;
            }
        }
        
        void NkTimer::Stop() {
            mIsRunning = false;
        }
        
        void NkTimer::Reset() {
            mLastTick = NkClock::Now();
        }
        
        void NkTimer::Update() {
            if (!mIsRunning || !mCallback) return;
            
            NkClock::TimePoint now = NkClock::Now();
            NkDuration elapsed = now - mLastTick;
            
            if (elapsed >= mInterval) {
                mCallback->OnTimer();
                
                if (mAutoReset) {
                    mLastTick = now;
                } else {
                    mIsRunning = false;
                }
            }
        }
        
        void NkTimer::SetCallback(NkTimerCallback* callback) {
            mCallback = callback;
        }
        
        void NkTimer::SetInterval(const NkDuration& interval) {
            mInterval = interval;
        }
        
        void NkTimer::SetAutoReset(bool autoReset) {
            mAutoReset = autoReset;
        }
        
        bool NkTimer::IsRunning() const {
            return mIsRunning;
        }
        
        NkDuration NkTimer::GetInterval() const {
            return mInterval;
        }
        
        NkDuration NkTimer::GetElapsed() const {
            if (!mIsRunning) return NkDuration::Zero();
            
            NkClock::TimePoint now = NkClock::Now();
            return now - mLastTick;
        }
        
        NkDuration NkTimer::GetRemaining() const {
            NkDuration elapsed = GetElapsed();
            if (elapsed >= mInterval) {
                return NkDuration::Zero();
            }
            return mInterval - elapsed;
        }
        
        f64 NkTimer::GetProgress() const {
            if (mInterval.IsZero()) return 0.0;
            
            NkDuration elapsed = GetElapsed();
            return elapsed.ToSecondsF() / mInterval.ToSecondsF();
        }
        
    } // namespace entseu
} // namespace nkentseu

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================