// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkTimer.h
// DESCRIPTION: Timer with callback support
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKTIMER_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKTIMER_H_INCLUDED

#include "../Core/NkTypes.h"
#include "NkClock.h"
#include "NkDuration.h"

namespace nkentseu {
    namespace entseu {
        
        /**
         * @brief Timer callback interface
         */
        class NkTimerCallback {
        public:
            virtual ~NkTimerCallback() {}
            virtual void OnTimer() = 0;
        };
        
        /**
         * @brief Timer class
         * 
         * Timer qui appelle un callback à intervalle régulier.
         * 
         * @example
         * class MyCallback : public NkTimerCallback {
         *     void OnTimer() override {
         *         printf("Tick!\n");
         *     }
         * };
         * 
         * MyCallback callback;
         * NkTimer timer(&callback, NkDuration::FromSeconds(1));
         * timer.Start();  // Calls callback every second
         */
        class NkTimer {
        private:
            NkTimerCallback* mCallback;
            NkDuration mInterval;
            NkClock::TimePoint mLastTick;
            bool mIsRunning;
            bool mAutoReset;  // Restart after each tick
            
        public:
            // Constructors
            NkTimer();
            NkTimer(NkTimerCallback* callback, const NkDuration& interval, bool autoReset = true);
            
            // Control
            void Start();
            void Stop();
            void Reset();
            
            // Update (call in main loop)
            void Update();
            
            // Configuration
            void SetCallback(NkTimerCallback* callback);
            void SetInterval(const NkDuration& interval);
            void SetAutoReset(bool autoReset);
            
            // State
            bool IsRunning() const;
            NkDuration GetInterval() const;
            NkDuration GetElapsed() const;
            NkDuration GetRemaining() const;
            f64 GetProgress() const;  // 0.0 to 1.0
        };
        
        /**
         * @brief Simple function pointer timer (C++11)
         */
        #if defined(NK_CPP11)
        class NkSimpleTimer : public NkTimerCallback {
        private:
            NkTimer mTimer;
            
        public:
            using CallbackFunc = void(*)();
            CallbackFunc OnTick;
            
            NkSimpleTimer(const NkDuration& interval, bool autoReset = true)
                : mTimer(this, interval, autoReset)
                , OnTick(nullptr) {
            }
            
            void OnTimer() override {
                if (OnTick) OnTick();
            }
            
            void Start() { mTimer.Start(); }
            void Stop() { mTimer.Stop(); }
            void Update() { mTimer.Update(); }
            bool IsRunning() const { return mTimer.IsRunning(); }
        };
        #endif
        
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKTIMER_H_INCLUDED

// ============================================================
// Copyright © 2024-2026 Rihen. All rights reserved.
// Proprietary License - Free to use and modify
//
// Generated by Rihen on 2026-02-05 22:26:13
// Creation Date: 2026-02-05 22:26:13
// ============================================================