// -----------------------------------------------------------------------------
// FICHIER: Core\Nkentseu\src\Nkentseu\Time\NkTimestamp.h
// DESCRIPTION: Timestamp with date and time
// AUTEUR: Rihen
// DATE: 2026-02-10
// VERSION: 1.0.0
// -----------------------------------------------------------------------------

#pragma once

#ifndef NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKTIMESTAMP_H_INCLUDED
#define NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKTIMESTAMP_H_INCLUDED

#include "../Core/NkTypes.h"
#include "../Core/NkString.h"
#include "NkDuration.h"

namespace nkentseu {
    namespace entseu {
        
        /**
         * @brief DateTime structure
         */
        struct NkDateTime {
            i32 Year;
            i32 Month;      // 1-12
            i32 Day;        // 1-31
            i32 Hour;       // 0-23
            i32 Minute;     // 0-59
            i32 Second;     // 0-59
            i32 Millisecond; // 0-999
            i32 DayOfWeek;  // 0=Sunday, 6=Saturday
            
            NkDateTime();
        };
        
        /**
         * @brief Timestamp class
         * 
         * Représente un point dans le temps (date + heure).
         * Basé sur Unix epoch (01/01/1970 00:00:00 UTC).
         * 
         * @example
         * NkTimestamp now = NkTimestamp::Now();
         * auto str = now.ToString();  // "2026-02-10 14:30:45"
         * 
         * auto dt = now.ToDateTime();
         * printf("%d-%02d-%02d\n", dt.Year, dt.Month, dt.Day);
         */
        class NkTimestamp {
        private:
            i64 mUnixTimestamp;  // Milliseconds since epoch
            
        public:
            // Constructors
            NkTimestamp();
            explicit NkTimestamp(i64 unixTimestamp);
            NkTimestamp(const NkTimestamp& other);
            
            // Assignment
            NkTimestamp& operator=(const NkTimestamp& other);
            
            // Factory methods
            static NkTimestamp Now();
            static NkTimestamp FromUnixTimestamp(i64 milliseconds);
            static NkTimestamp FromDateTime(const NkDateTime& dt);
            static NkTimestamp FromString(const char* str);  // ISO 8601
            
            // Conversion
            i64 ToUnixTimestamp() const;
            NkDateTime ToDateTime() const;
            core::NkString ToString() const;  // ISO 8601: "YYYY-MM-DD HH:MM:SS"
            core::NkString ToStringISO() const;  // Full ISO 8601
            core::NkString ToStringDate() const;  // "YYYY-MM-DD"
            core::NkString ToStringTime() const;  // "HH:MM:SS"
            
            // Arithmetic
            NkTimestamp operator+(const NkDuration& duration) const;
            NkTimestamp operator-(const NkDuration& duration) const;
            NkDuration operator-(const NkTimestamp& other) const;
            
            NkTimestamp& operator+=(const NkDuration& duration);
            NkTimestamp& operator-=(const NkDuration& duration);
            
            // Comparison
            bool operator==(const NkTimestamp& other) const;
            bool operator!=(const NkTimestamp& other) const;
            bool operator<(const NkTimestamp& other) const;
            bool operator<=(const NkTimestamp& other) const;
            bool operator>(const NkTimestamp& other) const;
            bool operator>=(const NkTimestamp& other) const;
            
            // Utilities
            bool IsValid() const;
            i32 GetYear() const;
            i32 GetMonth() const;
            i32 GetDay() const;
            i32 GetHour() const;
            i32 GetMinute() const;
            i32 GetSecond() const;
            i32 GetDayOfWeek() const;
            
            // Add time components
            NkTimestamp AddYears(i32 years) const;
            NkTimestamp AddMonths(i32 months) const;
            NkTimestamp AddDays(i32 days) const;
            NkTimestamp AddHours(i32 hours) const;
            NkTimestamp AddMinutes(i32 minutes) const;
            NkTimestamp AddSeconds(i32 seconds) const;
        };
        
    } // namespace entseu
} // namespace nkentseu

#endif // NK_CORE_NKENTSEU_SRC_NKENTSEU_TIME_NKTIMESTAMP_H_INCLUDED

    // ============================================================
    // Copyright © 2024-2026 Rihen. All rights reserved.
    // Proprietary License - Free to use and modify
    //
    // Generated by Rihen on 2026-02-05 22:26:13
    // Creation Date: 2026-02-05 22:26:13
    // ============================================================