"""
Init command - Initialize Jenga in existing project
"""

def execute(args):
    """Convert existing project to Jenga"""
    import os
    from pathlib import Path
    
    print("🔍 Analyzing project structure...")
    
    # Détecter les fichiers sources
    cpp_files = list(Path(".").rglob("*.cpp"))
    h_files = list(Path(".").rglob("*.h"))
    
    if not cpp_files:
        print("❌ No C++ files found")
        return 1
    
    # Détecter la structure
    has_src = Path("src").exists()
    has_include = Path("include").exists()
    
    project_name = Path.cwd().name
    
    print(f"📊 Found:")
    print(f"   {len(cpp_files)} C++ files")
    print(f"   {len(h_files)} Header files")
    print(f"   src/ directory: {'✅' if has_src else '❌'}")
    print(f"   include/ directory: {'✅' if has_include else '❌'}")
    
    # Créer .jenga
    jenga_content = f'''# {project_name}
# Generated by Jenga Init

with workspace("{project_name}"):
    configurations(["Debug", "Release"])
    
    with project("{project_name}"):
        consoleapp()
        language("C++")
        cppdialect("C++17")
        
        files(["{'src/' if has_src else ''}**.cpp"])
        {'includedirs(["include"])' if has_include else ''}
        
        targetdir("Build/Bin/%{{cfg.buildcfg}}")
'''
    
    jenga_file = Path(f"{project_name.lower()}.jenga")
    jenga_file.write_text(jenga_content)
    
    print(f"\n✅ Created: {jenga_file}")
    print(f"\n🚀 Next steps:")
    print(f"   jenga build")
    
    return 0