# Jenga/core/api.pyi
"""
Type stubs pour Jenga Build System API
Fournit l'autocomplétion et le type checking pour les fichiers .jenga
"""

# Import all API functions to make them available in .nken files
from api import *

from typing import List, Dict, Optional, Any, Union, Callable, TypeVar, Generic, ContextManager
from typing_extensions import Self
from pathlib import Path
from enum import Enum
from dataclasses import dataclass
from types import TracebackType

_T = TypeVar('_T')

__all__ = [
    # Context managers
    'workspace', 'project', 'toolchain', 'filter', 'test',
    
    # Workspace configuration
    'configurations', 'platforms', 'startproject', 'location',
    
    # Project kinds
    'consoleapp', 'windowedapp', 'staticlib', 'sharedlib', 'testsuite',
    
    # Language settings
    'language', 'cppdialect', 'cdialect',
    
    # Files
    'files', 'excludefiles', 'excludemainfiles',
    
    # Precompiled Headers
    'pchheader', 'pchsource',
    
    # Directories
    'includedirs', 'libdirs', 'objdir', 'targetdir', 'targetname',
    
    # Linking
    'links', 'dependson',
    
    # Dependencies and Resources
    'dependfiles', 'embedresources',
    
    # Compiler settings
    'defines', 'optimize', 'symbols', 'warnings',
    
    # Build hooks
    'prebuild', 'postbuild', 'prelink', 'postlink',
    
    # Toolchain selection
    'usetoolchain',
    
    # Android settings
    'androidsdkpath', 'androidndkpath', 'javajdkpath',
    'androidapplicationid', 'androidversioncode', 'androidversionname',
    'androidminsdk', 'androidtargetsdk',
    'androidsign', 'androidkeystore', 'androidkeystorepass', 'androidkeyalias',
    
    # Test settings
    'testoptions', 'testfiles', 'testmainfile', 'testmaintemplate',
    
    # Other
    'systemversion',
    
    # Toolchain settings
    'cppcompiler', 'ccompiler', 'toolchaindir',
]

# ============================================================================
# ENUMS
# ============================================================================

class ProjectKind(Enum):
    CONSOLE_APP: str
    WINDOWED_APP: str
    STATIC_LIB: str
    SHARED_LIB: str
    TEST_SUITE: str

class Language(Enum):
    C: str
    CPP: str
    OBJC: str
    OBJCPP: str

class Optimization(Enum):
    OFF: str
    SIZE: str
    SPEED: str
    FULL: str

# ============================================================================
# DATACLASSES
# ============================================================================

@dataclass
class Toolchain:
    name: str
    compiler: str
    ccompiler: Optional[str] = ...
    cppcompiler: Optional[str] = ...
    linker: Optional[str] = ...
    archiver: Optional[str] = ...
    sysroot: Optional[str] = ...
    targettriple: Optional[str] = ...
    compiler_path: Optional[str] = ...
    ccompiler_path: Optional[str] = ...
    cppcompiler_path: Optional[str] = ...
    linker_path: Optional[str] = ...
    archiver_path: Optional[str] = ...
    toolchain_dir: Optional[str] = ...
    defines: List[str] = ...
    flags: Dict[str, List[str]] = ...
    cflags: List[str] = ...
    cxxflags: List[str] = ...
    ldflags: List[str] = ...

@dataclass
class Project:
    name: str
    kind: ProjectKind = ...
    language: Language = ...
    location: str = ...
    cppdialect: str = ...
    cdialect: str = ...
    files: List[str] = ...
    excludefiles: List[str] = ...
    excludemainfiles: List[str] = ...
    pchheader: str = ...
    pchsource: str = ...
    includedirs: List[str] = ...
    libdirs: List[str] = ...
    objdir: str = ...
    targetdir: str = ...
    targetname: str = ...
    links: List[str] = ...
    dependson: List[str] = ...
    dependfiles: List[str] = ...
    embedresources: List[str] = ...
    defines: List[str] = ...
    optimize: Optimization = ...
    symbols: bool = ...
    warnings: str = ...
    toolchain: Optional[str] = ...
    prebuildcommands: List[str] = ...
    postbuildcommands: List[str] = ...
    prelinkcommands: List[str] = ...
    postlinkcommands: List[str] = ...
    system_defines: Dict[str, List[str]] = ...
    system_links: Dict[str, List[str]] = ...
    androidapplicationid: str = ...
    androidversioncode: int = ...
    androidversionname: str = ...
    androidminsdk: int = ...
    androidtargetsdk: int = ...
    androidsign: bool = ...
    androidkeystore: str = ...
    androidkeystorepass: str = ...
    androidkeyalias: str = ...
    iosbundleid: str = ...
    iosversion: str = ...
    iosminsdk: str = ...
    is_test: bool = ...
    parent_project: Optional[str] = ...
    testoptions: List[str] = ...
    testfiles: List[str] = ...
    testmainfile: str = ...
    testmaintemplate: str = ...
    _current_filter: Optional[str] = ...
    _filtered_defines: Dict[str, List[str]] = ...
    _filtered_optimize: Dict[str, Optimization] = ...
    _filtered_symbols: Dict[str, bool] = ...
    _explicit_toolchain: bool = ...

@dataclass
class Workspace:
    name: str
    location: str = ...
    configurations: List[str] = ...
    platforms: List[str] = ...
    startproject: str = ...
    projects: Dict[str, Project] = ...
    toolchains: Dict[str, Toolchain] = ...
    toolchain: Optional[str] = ...
    androidsdkpath: str = ...
    androidndkpath: str = ...
    javajdkpath: str = ...
    _current_project: Optional[Project] = ...
    _current_toolchain: Optional[Toolchain] = ...

@dataclass
class ToolConfig:
    name: str
    type: str
    version: str = ...
    path: str = ...
    cc: str = ...
    cxx: str = ...
    ar: str = ...
    ld: str = ...
    strip: str = ...
    ranlib: str = ...
    sdk_path: str = ...
    include_paths: List[str] = ...
    library_paths: List[str] = ...
    frameworks: List[str] = ...
    env_vars: Dict[str, str] = ...
    cflags: List[str] = ...
    cxxflags: List[str] = ...
    ldflags: List[str] = ...
    sysroot: str = ...
    target_triple: str = ...
    validated: bool = ...
    validation_error: str = ...
    def validate(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...

# ============================================================================
# CONTEXT MANAGERS (Corrected)
# ============================================================================

class workspace:
    """Workspace context manager"""
    def __init__(self, name: str) -> None: ...
    def __enter__(self) -> Workspace: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...

class project:
    """Project context manager"""
    def __init__(self, name: str) -> None: ...
    def __enter__(self) -> Project: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...

class toolchain:
    """Toolchain context manager"""
    def __init__(self, name: str, compiler: str) -> None: ...
    def __enter__(self) -> Toolchain: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...

class filter:
    """Filter context manager for conditional settings"""
    def __init__(self, filter_expr: str) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...

class test:
    """Test suite context manager"""
    def __init__(self, subname: str) -> None: ...
    def __enter__(self) -> Project: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...

class include:
    """Include external .jenga files"""
    def __init__(self, jenga_file: str) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...
    def only(self, project_names: List[str]) -> Self: ...
    def skip(self, project_names: List[str]) -> Self: ...
    def getprojects(self) -> Dict[str, Project]: ...
    def getproject(self, name: str) -> Optional[Project]: ...

class batch_include:
    """Include multiple .jenga files at once"""
    def __init__(self, includes: Union[List[str], Dict[str, Optional[List[str]]]]) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...

class addtools:
    """Add external tools to build system"""
    def __init__(self, tools_config: Union[str, Dict[str, Any]], activate: bool = True) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...
    def get_tool_config(self, name: str) -> Optional[ToolConfig]: ...
    def list_loaded_tools(self) -> List[str]: ...
    def activate_tool(self, name: str) -> bool: ...
    def deactivate_tool(self, name: str) -> bool: ...

# ============================================================================
# WORKSPACE API FUNCTIONS
# ============================================================================

def configurations(configs: List[str]) -> None: ...
def platforms(plats: List[str]) -> None: ...
def startproject(name: str) -> None: ...
def androidsdkpath(path: str) -> None: ...
def androidndkpath(path: str) -> None: ...
def javajdkpath(path: str) -> None: ...

# ============================================================================
# PROJECT KIND FUNCTIONS
# ============================================================================

def consoleapp() -> None: ...
def windowedapp() -> None: ...
def staticlib() -> None: ...
def sharedlib() -> None: ...
def androidapp() -> None: ...
def iosapp() -> None: ...
def testsuite() -> None: ...

# ============================================================================
# LANGUAGE FUNCTIONS
# ============================================================================

def language(lang: str) -> None: ...
def cppdialect(dialect: str) -> None: ...
def cdialect(dialect: str) -> None: ...

# ============================================================================
# PROJECT LOCATION
# ============================================================================

def location(path: str) -> None: ...

# ============================================================================
# FILE FUNCTIONS
# ============================================================================

def files(file_list: List[str]) -> None: ...
def excludefiles(file_list: List[str]) -> None: ...
def removefiles(file_list: List[str]) -> None: ...
def excludemainfiles(file_list: List[str]) -> None: ...
def removemainfiles(file_list: List[str]) -> None: ...

# ============================================================================
# DIRECTORY FUNCTIONS
# ============================================================================

def includedirs(dirs: List[str]) -> None: ...
def libdirs(dirs: List[str]) -> None: ...
def objdir(dir_path: str) -> None: ...
def targetdir(dir_path: str) -> None: ...
def targetname(name: str) -> None: ...

# ============================================================================
# LINKING FUNCTIONS
# ============================================================================

def links(link_list: List[str]) -> None: ...
def dependson(deps: List[str]) -> None: ...
def dependfiles(patterns: List[str]) -> None: ...

# ============================================================================
# COMPILER SETTINGS
# ============================================================================

def defines(defs: List[str]) -> None: ...
def optimize(level: str) -> None: ...
def symbols(enable: str) -> None: ...
def warnings(level: str) -> None: ...

# ============================================================================
# PRECOMPILED HEADERS
# ============================================================================

def pchheader(header: str) -> None: ...
def pchsource(source: str) -> None: ...

# ============================================================================
# EMBEDDED RESOURCES
# ============================================================================

def embedresources(resources: List[str]) -> None: ...

# ============================================================================
# ANDROID SETTINGS
# ============================================================================

def androidapplicationid(app_id: str) -> None: ...
def androidversioncode(code: int) -> None: ...
def androidversionname(name: str) -> None: ...
def androidminsdk(sdk: int) -> None: ...
def androidtargetsdk(sdk: int) -> None: ...
def androidcompilesdk(sdk: int) -> None: ...
def androidabis(abis: List[str]) -> None: ...
def androidproguard(enable: bool = True) -> None: ...
def androidproguardrules(rules: List[str]) -> None: ...
def androidassets(asset_patterns: List[str]) -> None: ...
def androidpermissions(permissions: List[str]) -> None: ...
def androidnativeactivity(enable: bool = True) -> None: ...
def ndkversion(version: str) -> None: ...
def androidsign(enable: bool = True) -> None: ...
def androidkeystore(path: str) -> None: ...
def androidkeystorepass(password: str) -> None: ...
def androidkeyalias(alias: str) -> None: ...

# ============================================================================
# IOS SETTINGS
# ============================================================================

def iosbundleid(bundle_id: str) -> None: ...
def iosversion(version: str) -> None: ...
def iosminsdk(min_sdk: str) -> None: ...

# ============================================================================
# TEST SETTINGS
# ============================================================================

def testoptions(opts: List[str]) -> None: ...
def testfiles(patterns: List[str]) -> None: ...
def testmainfile(main_file: str) -> None: ...
def testmaintemplate(template_file: str) -> None: ...

# ============================================================================
# BUILD HOOKS
# ============================================================================

def prebuild(commands: List[str]) -> None: ...
def postbuild(commands: List[str]) -> None: ...
def prelink(commands: List[str]) -> None: ...
def postlink(commands: List[str]) -> None: ...

# ============================================================================
# TOOLCHAIN FUNCTIONS
# ============================================================================

def cppcompiler(compiler_path: str) -> None: ...
def ccompiler(compiler_path: str) -> None: ...
def linker(linker_path: str) -> None: ...
def archiver(archiver_path: str) -> None: ...
def toolchaindir(path: str) -> None: ...
def sysroot(path: str) -> None: ...
def targettriple(triple: str) -> None: ...
def usetoolchain(name: str) -> None: ...
def flags(flag_type: str, flag_list: List[str]) -> None: ...
def cflags(flag_list: List[str]) -> None: ...
def cxxflags(flag_list: List[str]) -> None: ...
def ldflags(flag_list: List[str]) -> None: ...
def linkerflags(flag_list: List[str]) -> None: ...

# ============================================================================
# ADVANCED TOOLCHAIN FUNCTIONS
# ============================================================================

def addflag(flag: str) -> None: ...
def addcflag(flag: str) -> None: ...
def addcxxflag(flag: str) -> None: ...
def addldflag(flag: str) -> None: ...
def adddefine(define: str) -> None: ...
def framework(framework_name: str) -> None: ...
def librarypath(path: str) -> None: ...
def library(lib_name: str) -> None: ...
def rpath(path: str) -> None: ...
def nostdlib() -> None: ...
def nostdinc() -> None: ...
def pic() -> None: ...
def pie() -> None: ...
def sanitize(sanitizer: str) -> None: ...
def nowarnings() -> None: ...
def profile(enable: bool = True) -> None: ...
def coverage(enable: bool = True) -> None: ...
def encoding(value: str = "utf-8") -> None: ...
def consoleencoding(compiler: str, encoding: str, *, cflags: Optional[List[str]] = None, cxxflags: Optional[List[str]] = None) -> None: ...
def warnings_tc(warning_level: str) -> None: ...
def optimization_tc(level: str) -> None: ...
def debug_tc(enable: bool = True) -> None: ...
def debug(enable: bool = True) -> None: ...
def optimization(level: str) -> None: ...

# ============================================================================
# BUILD OPTIONS
# ============================================================================

def buildoption(option: str, values: List[str]) -> None: ...
def buildoptions(options_dict: Dict[str, Union[List[str], str]]) -> None: ...

# ============================================================================
# EXTERNAL PROJECT INCLUSION
# ============================================================================

def addprojects(jenga_file: str, projects: Optional[List[str]] = None) -> List[str]: ...
def useproject(project_name: str, copy_includes: bool = True, copy_defines: bool = True) -> None: ...
def getpp(project_name: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
def listincludes() -> List[Dict[str, Any]]: ...
def validateincludes() -> None: ...
def getincludeinfo(project_name: str) -> Optional[Dict[str, Any]]: ...
def include_from_directory(directory: str, pattern: str = "*.jenga") -> List[str]: ...
def getincludedprojects() -> Dict[str, Dict[str, Any]]: ...
def getprojectinfo(project_name: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
def listallprojects() -> List[Dict[str, Any]]: ...
def generatedependencyreport() -> None: ...
def lip() -> List[Dict[str, Any]]: ...
def vip() -> None: ...

# ============================================================================
# EXTERNAL TOOLS
# ============================================================================

def addexternaltools(tools_config: Union[str, Dict[str, Any]], activate: bool = True) -> None: ...
def usetool(tool_name: str) -> None: ...
def listtools() -> List[Dict[str, Any]]: ...
def gettoolinfo(tool_name: str) -> Optional[Dict[str, Any]]: ...
def validatetools() -> List[Dict[str, Any]]: ...
def create_android_ndk_tool(ndk_path: str, api_level: int = 21, arch: str = "arm64-v8a") -> Dict[str, Any]: ...
def create_emscripten_tool(emsdk_path: str) -> Dict[str, Any]: ...
def create_custom_gcc_tool(gcc_path: str, version: str = "") -> Dict[str, Any]: ...
def get_current_toolchain_config() -> Optional[Dict[str, Any]]: ...
def inject_tool_flags_into_toolchain() -> None: ...
def init_tools_system() -> None: ...

# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def get_current_workspace() -> Optional[Workspace]: ...
def reset_state() -> None: ...
def systemversion(version: str) -> None: ...

# ============================================================================
# CONSTANTS
# ============================================================================

ANDROID_PERMISSIONS_REFERENCE: str
PROGUARD_TEMPLATES: str