# Auto-generated by 'jenga install toolchain'.
# Optional import helper for workspace scripts.
from Jenga import *

def RegisterJengaGlobalToolchains():
    """Register toolchains installed in Jenga global registry."""
    with toolchain("android-ndk", "android-ndk"):
        settarget("Android", "arm64", "android")
        ccompiler(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\clang")
        cppcompiler(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++")
        linker(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\ld")
        archiver(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-ar")
    with toolchain("clang-cl", "clang"):
        settarget("Windows", "x86_64", "msvc")
        ccompiler(r"C:\msys64\ucrt64\bin\clang-cl.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang-cl.EXE")
        linker(r"C:\msys64\ucrt64\bin\clang-cl.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")
    with toolchain("clang-cross-linux", "clang"):
        settarget("Linux", "x86_64", "gnu")
        targettriple(r"x86_64-unknown-linux-gnu")
        ccompiler(r"C:\msys64\ucrt64\bin\clang.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang++.EXE")
        linker(r"C:\msys64\ucrt64\bin\clang++.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")
        cflags(["--target=x86_64-unknown-linux-gnu"])
        cxxflags(["--target=x86_64-unknown-linux-gnu"])
        ldflags(["--target=x86_64-unknown-linux-gnu"])
    with toolchain("clang-mingw", "clang"):
        settarget("Windows", "x86_64", "mingw")
        ccompiler(r"C:\msys64\ucrt64\bin\clang.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang++.EXE")
        linker(r"C:\msys64\ucrt64\bin\clang++.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")
    with toolchain("emscripten", "emscripten"):
        settarget("Web", "wasm32")
        ccompiler(r"C:\emsdk-4.0.22\upstream\emscripten\emcc.BAT")
        cppcompiler(r"C:\emsdk-4.0.22\upstream\emscripten\em++.bat")
        archiver(r"C:\emsdk-4.0.22\upstream\emscripten\emar.bat")
    with toolchain("host-clang", "clang"):
        settarget("Windows", "x86_64", "mingw")
        ccompiler(r"C:\msys64\ucrt64\bin\clang.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang++.EXE")
        linker(r"C:\msys64\ucrt64\bin\ld.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")
    with toolchain("mingw", "gcc"):
        settarget("Windows", "x86_64", "mingw")
        ccompiler(r"C:\msys64\ucrt64\bin\x86_64-w64-mingw32-gcc.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\x86_64-w64-mingw32-g++.EXE")
        linker(r"C:\msys64\ucrt64\bin\ld.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")
    with toolchain("zig-linux-x64", "clang"):
        settarget("Linux", "x86_64", "gnu")
        targettriple(r"x86_64-linux-gnu")
        # Use wrappers that translate standard syntax to Zig syntax
        ccompiler(r"E:\Projets\Closed\Jenga\scripts\zig-cc.bat")
        cppcompiler(r"E:\Projets\Closed\Jenga\scripts\zig-c++.bat")
        linker(r"E:\Projets\Closed\Jenga\scripts\zig-c++.bat")
        archiver(r"C:\Zig\zig-x86_64-windows-0.16.0\zig.exe")
        cflags(["-target", "x86_64-linux-gnu"])
        cxxflags(["-target", "x86_64-linux-gnu", "-std=c++17"])
        ldflags(["-target", "x86_64-linux-gnu"])
        arflags(["ar"])


def ToolchainAndroidNDK():
    """Register android-ndk toolchain."""
    with toolchain("android-ndk", "android-ndk"):
        settarget("Android", "arm64", "android")
        ccompiler(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\clang")
        cppcompiler(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++")
        linker(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\ld")
        archiver(r"C:\Android\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-ar")

def ToolchainClangCl():
    """Register clang-cl toolchain."""
    with toolchain("clang-cl", "clang"):
        settarget("Windows", "x86_64", "msvc")
        ccompiler(r"C:\msys64\ucrt64\bin\clang-cl.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang-cl.EXE")
        linker(r"C:\msys64\ucrt64\bin\clang-cl.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")

def ToolchainClangCrossLinux():
    """Register clang-cross-linux toolchain."""
    with toolchain("clang-cross-linux", "clang"):
        settarget("Linux", "x86_64", "gnu")
        targettriple(r"x86_64-unknown-linux-gnu")
        ccompiler(r"C:\msys64\ucrt64\bin\clang.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang++.EXE")
        linker(r"C:\msys64\ucrt64\bin\clang++.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")
        cflags(["--target=x86_64-unknown-linux-gnu"])
        cxxflags(["--target=x86_64-unknown-linux-gnu"])
        ldflags(["--target=x86_64-unknown-linux-gnu"])

def ToolchainClangMinGW():
    """Register clang-mingw toolchain."""
    with toolchain("clang-mingw", "clang"):
        settarget("Windows", "x86_64", "mingw")
        ccompiler(r"C:\msys64\ucrt64\bin\clang.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang++.EXE")
        linker(r"C:\msys64\ucrt64\bin\clang++.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")

def ToolchainEmscripten():
    """Register emscripten toolchain."""
    with toolchain("emscripten", "emscripten"):
        settarget("Web", "wasm32")
        ccompiler(r"C:\emsdk-4.0.22\upstream\emscripten\emcc.BAT")
        cppcompiler(r"C:\emsdk-4.0.22\upstream\emscripten\em++.bat")
        archiver(r"C:\emsdk-4.0.22\upstream\emscripten\emar.bat")

def ToolchainHostClang():
    """Register host-clang toolchain."""
    with toolchain("host-clang", "clang"):
        settarget("Windows", "x86_64", "mingw")
        ccompiler(r"C:\msys64\ucrt64\bin\clang.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\clang++.EXE")
        linker(r"C:\msys64\ucrt64\bin\ld.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")

def ToolchainMinGW():
    """Register mingw toolchain."""
    with toolchain("mingw", "gcc"):
        settarget("Windows", "x86_64", "mingw")
        ccompiler(r"C:\msys64\ucrt64\bin\x86_64-w64-mingw32-gcc.EXE")
        cppcompiler(r"C:\msys64\ucrt64\bin\x86_64-w64-mingw32-g++.EXE")
        linker(r"C:\msys64\ucrt64\bin\ld.EXE")
        archiver(r"C:\msys64\ucrt64\bin\ar.EXE")

def ToolchainZigLinuxX64():
    """Register zig-linux-x64 toolchain."""
    with toolchain("zig-linux-x64", "clang"):
        settarget("Linux", "x86_64", "gnu")
        targettriple(r"x86_64-linux-gnu")
        # Use wrappers that translate standard syntax to Zig syntax
        ccompiler(r"E:\Projets\Closed\Jenga\scripts\zig-cc.bat")
        cppcompiler(r"E:\Projets\Closed\Jenga\scripts\zig-c++.bat")
        linker(r"E:\Projets\Closed\Jenga\scripts\zig-c++.bat")
        archiver(r"C:\Zig\zig-x86_64-windows-0.16.0\zig.exe")
        cflags(["-target", "x86_64-linux-gnu"])
        cxxflags(["-target", "x86_64-linux-gnu", "-std=c++17"])
        ldflags(["-target", "x86_64-linux-gnu"])
        arflags(["ar"])